resolver: nightly-2024-10-21
# If you update the snapshot, also update .github/workflows/stack.yml to the matching GHC version

packages:
- system-fileio
- system-filepath

extra-deps:
- chell-0.5.0.2
- chell-quickcheck-0.2.5.4
- patience-0.3
