#!/bin/bash
if [ ! -f 'system-filepath.cabal' ]; then
	echo -n "Can't find system-filepath.cabal; please run this script as"
	echo -n " ./scripts/run-coverage from within the system-filepath source"
	echo " directory"
	exit 1
fi

. scripts/common.bash

require_cabal_dev

pushd tests
$CABAL_DEV -s ../cabal-dev install --flags="coverage" || exit 1
popd

rm -f system-filepath_tests.tix
cabal-dev/bin/system-filepath_tests $@

hpc markup --srcdir=src --srcdir=tests/ system-filepath_tests.tix --destdir=hpc-markup --exclude=Main
hpc report --srcdir=src --srcdir=tests/ system-filepath_tests.tix --exclude=Main
